"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";

function reasonLine(reason: string | null) {
  if (reason === "shuffle") return "you’ve reached today’s shuffle.";
    if (reason === "listen") return "you’ve reached today’s listening.";
      if (reason === "record") return "you’ve reached today’s recording.";
        return "stay longer.";
        }

        export default function PremiumPage() {
          const router = useRouter();
            const params = useSearchParams();

              const [code, setCode] = useState("");
                const [error, setError] = useState<string | null>(null);

                  // dev bypass: tap "premium." 7 times
                    const [taps, setTaps] = useState(0);
                      const [showDev, setShowDev] = useState(false);
                        const tapTimer = useRef<number | null>(null);

                          const reason = useMemo(() => params.get("reason"), [params]);

                            useEffect(() => {
                                if (taps >= 7) setShowDev(true);
                                  }, [taps]);

                                    const onTitleTap = () => {
                                        if (tapTimer.current) window.clearTimeout(tapTimer.current);
                                            setTaps((n) => n + 1);
                                                tapTimer.current = window.setTimeout(() => setTaps(0), 900);
                                                  };

                                                    const previous = () => router.push("/listening");

                                                      const unlock = () => {
                                                          localStorage.setItem("atln_premium", "1");
                                                              router.push("/listening");
                                                                };

                                                                  const lock = () => {
                                                                      localStorage.removeItem("atln_premium");
                                                                          router.push("/listening");
                                                                            };

                                                                              const submit = () => {
                                                                                  setError(null);
                                                                                      const c = code.trim().toLowerCase();

                                                                                          // ✅ change this code if you want
                                                                                              if (c === "premium") {
                                                                                                    unlock();
                                                                                                          return;
                                                                                                              }

                                                                                                                  setError("not today.");
                                                                                                                    };

                                                                                                                      return (
                                                                                                                          <main className="screen">
                                                                                                                                <section className="stack" aria-label="premium">
                                                                                                                                        <p className="mainLine fadeIn" onClick={onTitleTap} style={{ cursor: "default" }}>
                                                                                                                                                  premium.
                                                                                                                                                          </p>

                                                                                                                                                                  <p className="enterLine fadeIn" style={{ marginTop: 18 }}>
                                                                                                                                                                            {reasonLine(reason)}
                                                                                                                                                                                    </p>

                                                                                                                                                                                            <div style={{ marginTop: 22, display: "grid", gap: 12, justifyItems: "center" }}>
                                                                                                                                                                                                      <input
                                                                                                                                                                                                                  value={code}
                                                                                                                                                                                                                              onChange={(e) => setCode(e.target.value)}
                                                                                                                                                                                                                                          placeholder="code"
                                                                                                                                                                                                                                                      autoCapitalize="none"
                                                                                                                                                                                                                                                                  autoCorrect="off"
                                                                                                                                                                                                                                                                              spellCheck={false}
                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                        width: "min(360px, 86vw)",
                                                                                                                                                                                                                                                                                                                      background: "rgba(255,255,255,0.03)",
                                                                                                                                                                                                                                                                                                                                    border: "1px solid rgba(235,235,235,0.20)",
                                                                                                                                                                                                                                                                                                                                                  color: "rgba(235,235,235,0.78)",
                                                                                                                                                                                                                                                                                                                                                                borderRadius: 999,
                                                                                                                                                                                                                                                                                                                                                                              padding: "12px 16px",
                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                          outline: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                        textAlign: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                      letterSpacing: "0.06em",
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button style={btnStyle(true)} onClick={submit}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  enter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="enterLine fadeIn" style={{ marginTop: 6 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button style={btnStyle(true)} onClick={previous}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            previous
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {showDev && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ marginTop: 10, display: "flex", gap: 10, justifyContent: "center", flexWrap: "wrap" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button style={btnStyle(true)} onClick={unlock}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          unlock
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button style={btnStyle(true)} onClick={lock}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      lock
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function btnStyle(enabled: boolean): React.CSSProperties {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: "transparent",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "1px solid rgba(235,235,235,0.35)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: enabled ? "rgba(235,235,235,0.75)" : "rgba(235,235,235,0.30)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "12px 18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: 999,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            letterSpacing: "0.08em",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cursor: enabled ? "pointer" : "not-allowed",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    opacity: enabled ? 1 : 0.6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }