"use client";

import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { getEntitlement, setEntitlement } from "@/lib/entitlements";

export default function PremiumPage() {
  const router = useRouter();
    const params = useSearchParams();

      const [code, setCode] = useState("");
        const [msg, setMsg] = useState<string | null>(null);

          // hidden dev unlock
            const [tapCount, setTapCount] = useState(0);
              const [devVisible, setDevVisible] = useState(false);

                useEffect(() => {
                    // If user is already premium, don’t trap them here.
                        if (getEntitlement() === "premium") {
                              router.replace("/listening");
                                  }
                                      // eslint-disable-next-line react-hooks/exhaustive-deps
                                        }, []);

                                          const reason = params.get("reason"); // optional: "shuffle" | "listen" | "record"
                                            const reasonLine =
                                                reason === "shuffle"
                                                      ? "You’ve reached today’s shuffle."
                                                            : reason === "listen"
                                                                  ? "You’ve reached today’s listening."
                                                                        : reason === "record"
                                                                              ? "You’ve reached today’s telling."
                                                                                    : "You’ve reached today’s limit.";

                                                                                      const previous = () => {
                                                                                          router.push("/listening");
                                                                                            };

                                                                                              const onTitleTap = () => {
                                                                                                  const next = tapCount + 1;
                                                                                                      setTapCount(next);
                                                                                                          if (next >= 7) setDevVisible(true);
                                                                                                            };

                                                                                                              const enter = () => {
                                                                                                                  setMsg(null);

                                                                                                                      if (code.trim().toLowerCase() === "premium") {
                                                                                                                            setEntitlement("premium");
                                                                                                                                  router.push("/listening");
                                                                                                                                        return;
                                                                                                                                            }

                                                                                                                                                setMsg("Not yet.");
                                                                                                                                                  };

                                                                                                                                                    return (
                                                                                                                                                        <main className="screen">
                                                                                                                                                              <section className="stack" aria-label="Premium">
                                                                                                                                                                      <p
                                                                                                                                                                                className="mainLine fadeIn"
                                                                                                                                                                                          onClick={onTitleTap}
                                                                                                                                                                                                    style={{ cursor: "default", userSelect: "none" }}
                                                                                                                                                                                                            >
                                                                                                                                                                                                                      Premium.
                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                      <p className="enterLine fadeIn" style={{ marginTop: 18 }}>
                                                                                                                                                                                                                                                Stay longer.
                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                <div style={{ marginTop: 22, display: "grid", gap: 12, justifyItems: "center" }}>
                                                                                                                                                                                                                                                                          <p className="enterLine fadeIn" style={{ marginTop: 0 }}>
                                                                                                                                                                                                                                                                                      {reasonLine}
                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                          <div style={{ width: "min(720px, 92vw)", display: "grid", gap: 10 }}>
                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                    value={code}
                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setCode(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                placeholder="Code"
                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                              width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                              background: "rgba(255,255,255,0.03)",
                                                                                                                                                                                                                                                                                                                                                                                                                              border: "1px solid rgba(235,235,235,0.20)",
                                                                                                                                                                                                                                                                                                                                                                                                                                              color: "rgba(235,235,235,0.78)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: 999,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: "12px 16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              outline: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button style={btnStyle(true)} onClick={enter}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Enter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {msg && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="enterLine fadeIn" style={{ marginTop: 2 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {msg}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ display: "flex", gap: 12, justifyContent: "center", flexWrap: "wrap" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button className="fadeIn" style={btnStyle(true)} onClick={previous}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Previous
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button className="fadeIn" style={btnStyle(true)} onClick={() => router.push("/listening")}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Hidden dev row (tap "Premium." 7 times) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {devVisible && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ display: "flex", gap: 12, justifyContent: "center", flexWrap: "wrap" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={btnStyle(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setEntitlement("premium");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    router.push("/listening");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Unlock
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={btnStyle(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setEntitlement("free");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setMsg("Locked.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Lock
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function btnStyle(enabled: boolean): React.CSSProperties {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: "transparent",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: "1px solid rgba(235,235,235,0.35)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: enabled ? "rgba(235,235,235,0.75)" : "rgba(235,235,235,0.30)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: "12px 18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: 999,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      letterSpacing: "0.08em",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cursor: enabled ? "pointer" : "not-allowed",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              opacity: enabled ? 1 : 0.6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                