"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"

export default function RecordPage() {
  const router = useRouter()

    const [text, setText] = useState("")
      const [consent, setConsent] = useState(false)

        async function submit() {
            await fetch("/api/share", {
                  method: "POST",
                        headers: {
                                "Content-Type": "application/json"
                                      },
                                            body: JSON.stringify({
                                                    type: "text",
                                                            content: text
                                                                  })
                                                                      })

                                                                          router.push("/listening")
                                                                            }

                                                                              return (
                                                                                  <main className="screen">
                                                                                        <section className="stack">

                                                                                                {!consent && (
                                                                                                          <>
                                                                                                                      <textarea
                                                                                                                                    value={text}
                                                                                                                                                  onChange={(e) => setText(e.target.value)}
                                                                                                                                                                placeholder="write here..."
                                                                                                                                                                              style={{
                                                                                                                                                                                              width: "260px",
                                                                                                                                                                                                              height: "80px",
                                                                                                                                                                                                                              background: "rgba(255,255,255,0.05)",
                                                                                                                                                                                                                                              border: "1px solid rgba(255,255,255,0.2)",
                                                                                                                                                                                                                                                              color: "white",
                                                                                                                                                                                                                                                                              borderRadius: "8px",
                                                                                                                                                                                                                                                                                              padding: "10px",
                                                                                                                                                                                                                                                                                                              fontSize: "14px"
                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                    <div style={{ display: "flex", gap: "12px" }}>
                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => router.back()}
                                                                                                                                                                                                                                                                                                                                                                                                  className="pill"
                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                previous
                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => setConsent(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="pill"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {consent && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="mainLine fadeIn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  share anonymously?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ display: "flex", gap: "12px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setConsent(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="pill"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      previous
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={submit}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="pill"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                yes, continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }