"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"

export default function RecordPage() {
  const router = useRouter()

    const [text, setText] = useState("")
      const [showConsent, setShowConsent] = useState(false)
        const [submitting, setSubmitting] = useState(false)

          const handleSubmit = async () => {
              if (!text.trim()) return

                  setSubmitting(true)

                      await fetch("/api/share", {
                            method: "POST",
                                  headers: {
                                          "Content-Type": "application/json"
                                                },
                                                      body: JSON.stringify({
                                                              type: "text",
                                                                      content: text.trim()
                                                                            })
                                                                                })

                                                                                    router.push("/listening")
                                                                                      }

                                                                                        return (
                                                                                            <div className="min-h-screen flex flex-col items-center justify-center px-6">

                                                                                                  {!showConsent ? (
                                                                                                          <>
                                                                                                                    <textarea
                                                                                                                                value={text}
                                                                                                                                            onChange={(e) => setText(e.target.value)}
                                                                                                                                                        placeholder="write here..."
                                                                                                                                                                    className="w-full max-w-md border p-4 rounded-md mb-6"
                                                                                                                                                                              />

                                                                                                                                                                                        <div className="flex gap-4">
                                                                                                                                                                                                    <button
                                                                                                                                                                                                                  onClick={() => router.back()}
                                                                                                                                                                                                                                className="px-4 py-2 border rounded"
                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                          previous
                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                onClick={() => setShowConsent(true)}
                                                                                                                                                                                                                                                                                                              className="px-4 py-2 bg-black text-white rounded"
                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                        continue
                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                    <>
                                                                                                                                                                                                                                                                                                                                                                                              <p className="mb-6 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                          do you want to share this anonymously?
                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setShowConsent(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="px-4 py-2 border rounded"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                previous
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={handleSubmit}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    disabled={submitting}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="px-4 py-2 bg-black text-white rounded"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            yes, continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }